version: "3"

volumes:
  produtosdata:

networks:
  backend:

services:
  mysql:
    image: "mysql"
    volumes:
      - produtosdata:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - bind-adress=0.0.0.0
  mvc:
    build:
      context: mvc
      dockerfile: Dockerfile.dev
    networks:
      - backend
    ports:
      - 5000:80
    environment:
      - DBHOST=mysql
      - DBPORT=3306
      - DBPASSWORD=senha
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mysql
